paths:
  data_root: "./data"
  raw_data: "${paths.data_root}/raw"
  processed_data: "${paths.data_root}/processed"
  environment_assets: "./environment/assets"
  resources: "./resources"   # for db/tsv/etc
  models: "./models"
  #outputs: "./outputs"

colors:
  fg: "white"
  bg: "#e5231b"
  active_bg: "#9f9c93"
